In [1]:
import pandas as pd

In [6]:
pay = pd.read_csv('C:/Users/Raghib/Desktop/current-employee-names-salaries-and-position-titles-1.csv')

In [7]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,"$101,442.00",NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,"$94,122.00",NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,"$101,592.00",NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,"$110,064.00",NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,$19.86
...,...,...,...,...,...,...,...,...
33178,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,"$72,510.00",NaN
33179,"ZYMANTAS, LAURA C",POLICE OFFICER,POLICE,F,Salary,NaN,"$48,078.00",NaN
33180,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",NaN
33181,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,"$93,354.00",NaN
33182,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,"$115,932.00",NaN

In [8]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  object
 1   Job Titles         33183 non-null  object
 2   Department         33183 non-null  object
 3   Full or Part-Time  33183 non-null  object
 4   Salary or Hourly   33183 non-null  object
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  object
 7   Hourly Rate        8022 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

In [9]:
pay.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        25161
Annual Salary         8022
Hourly Rate          25161
dtype: int64

In [11]:
pay.describe()

       Typical Hours
count    8022.000000
mean       34.507604
std         9.252077
min        10.000000
25%        20.000000
50%        40.000000
75%        40.000000
max        40.000000

### 1. min,max and avg typical hour ?

In [33]:
print('Max Typicaal hours are:', pay['Typical Hours'].max())
print('Min Typicaal hours are:', pay['Typical Hours'].min())
print('Avg Typicaal hours are:', pay['Typical Hours'].mean())

Max Typicaal hours are: 40.0
Min Typicaal hours are: 10.0
Avg Typicaal hours are: 34.50760408875592

### 2. How many employ work on salary and how many employ work on hourly basis?

In [29]:
pay.groupby('Salary or Hourly')[['Salary or Hourly']].count()

                  Salary or Hourly
Salary or Hourly
Hourly                        8022
Salary                       25161

### 3. Which departnment has maximum no of emoloyee?

In [28]:
pay['Department'].value_counts().head(1)

Department
POLICE    13414
Name: count, dtype: int64

### 4. How many employee are salary and  how many employee are hourly basis in police ?

In [32]:
df=pay[pay['Department']=='POLICE']
df['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    13404
Hourly       10
Name: count, dtype: int64

### 5. What are the max,min and avg ?

In [39]:
pay['Salary'] = pay['Annual Salary'].str.replace('$','')
pay['Salary'] = pay['Salary'].str.replace(',','').astype(float)

In [38]:
print('Max Salary:', pay['Salary'].max())
print('Min Salary:', pay['Salary'].min())
print('Avg Salary:', pay['Salary'].mean())

Max Salary: 300000.0
Min Salary: 7200.0
Avg Salary: 86786.99979015141

### 6. Find the employee who has maximum salary ?

In [40]:
pay[pay['Salary']==pay['Salary'].max()][['Name','Salary']]

                  Name    Salary
8436  EVANS,  GINGER S  300000.0

### 6. Find the employee who has minimum salary ?

In [41]:
pay[pay['Salary']==pay['Salary'].min()][['Name','Salary']]

                       Name  Salary
2383  BLONSKI,  KATHERINE E  7200.0

### 7. What are the min,max and avg hourly rate ?

In [44]:
pay['H_Rate']=pay['Hourly Rate'].str.replace('$','').astype(float)
print('min H_Rate', pay ['H_Rate'].min())
print('max H_Rate', pay ['H_Rate'].max())
print('mean H_Rate', pay['H_Rate'].mean().round(2))

min H_Rate 2.65
max H_Rate 109.0
mean H_Rate 32.79

### 8. How many employee are getting max hourly rate ?

In [45]:
pay[pay['H_Rate']==pay['H_Rate'].max()].count()['Name']

np.int64(1)

### 9. Who is getting max hourly rate ?

In [46]:
pay[pay['H_Rate']==pay['H_Rate'].max()]['Name']

14534    JONES,  JOHN W
Name: Name, dtype: object

### 10. How many employee is getting less than avg hourly rate ?

In [48]:
pay[pay['H_Rate']<pay['H_Rate'].mean()].count()['Name']

np.int64(2922)

### 11. How many employees are paid hourly and they have full-time job?

In [50]:
pay[(pay['Salary or Hourly']=='Hourly') & (pay['Full or Part-Time']=='F')].count().head(1)

Name    5931
dtype: int64

### 12. Find the full-time employees who are working at less than hourly rate of $10.00?

In [52]:
pay[(pay['Full or Part-Time']=='F') & (pay['H_Rate']<10)]

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
30558,"VAZQUEZ, JENNIFER C",STUDENT INTERN - ALDERMANIC,CITY COUNCIL,F,Hourly,35.0,NaN,$9.50,NaN,9.5

### 13. How many unique Job Titles are there in the data?

In [53]:
pay['Job Titles'].nunique()

1111

### 14. What was the average Salary of the employees in each department?

In [55]:
pay.groupby('Department')[['Salary']].mean()

                             Salary
Department
ADMIN HEARNG           78683.692308
ANIMAL CONTRL          66197.612903
AVIATION               78750.549324
BOARD OF ELECTION      53548.149533
BOARD OF ETHICS        95061.000000
BUDGET & MGMT          91836.545455
BUILDINGS              99246.761041
BUSINESS AFFAIRS       80577.073171
CITY CLERK             70899.392857
CITY COUNCIL           64482.566801
COMMUNITY DEVELOPMENT  88430.778325
COPA                   76150.034483
CULTURAL AFFAIRS       89566.551724
DISABILITIES           83879.571429
DoIT                   99978.060606
FAMILY & SUPPORT       79895.762195
FINANCE                73781.255814
FIRE                   97958.600811
GENERAL SERVICES       83545.057116
HEALTH                 85557.501031
HUMAN RELATIONS        94819.500000
HUMAN RESOURCES        80230.560000
INSPECTOR GEN          79874.758621
LAW                    85958.321526
LICENSE APPL COMM      84420.000000
MAYOR'S OFFICE         98186.142857
OEMC                   74060.488299
POLICE                 86486.414503
POLICE BOARD           86136.000000
PROCUREMENT            83093.866667
PUBLIC LIBRARY         70750.407821
STREETS & SAN          83019.250000
TRANSPORTN             88657.905542
TREASURER              91832.863636
WATER MGMNT            89843.701639

### 15. What is the job title of 'KLUNK,  ROBERT E'?

In [57]:
pay[pay['Name']=='KLUNK,  ROBERT E'][['Job Titles']]

                Job Titles
15552  COMMITTEE SECRETARY

### 16. What are the top most common job titles?

In [58]:
pay['Job Titles'].value_counts().head(1)

Job Titles
POLICE OFFICER    9520
Name: count, dtype: int64

### 17. How many people have the word 'officer' in their job title?

In [65]:
pay[pay['Job Titles'].str.contains('officer',case=False)].count()['Name']

np.int64(11447)

### 18. Save the final dataframe to csv file ?

In [69]:
pay.to_csv('D:\\store.csv')